### ISSUE TITLE
Anon docker compose should be cached better

### ISSUE THREAD

**Issue by ShootingStar91** [nowcommunity/nowdatabase#110]
The dev docker setup was made to work via Dockerfile where `npm ci` is it's own layer and thus cached, so it doesn't have to be redone when re-creating container, only when earlier layers (package files) change.

This was then also done for the anon version, but it caused a problem with CI: cypress tests could not connect to frontend. I was unable to find why, so I reverted the change. This means running `npm run start:anon` will require reinstalling packages which is slow. It would be nice if this could be fixed.

**Comment by iritmaximus** [comment]
This is fixed.
