### ISSUE TITLE
Export refinements

### ISSUE THREAD

**Issue by ShootingStar91** [nowcommunity/nowdatabase#123]
**Combined locality & species export** now works in a simple way without server crashing. Here are some differences in current export to the legacy version, it should be discussed which of these have to be made similar in the new app and with what priority:

Current functionality:

- Exports all localities if user is Admin or Edit Unrestricted, otherwise (not logged in or other roles) will export only public localities and their species.
- Returns only the localities which user has filtered in the table
- The table's sorting is not respected, it is always A-Z by locality name as in the old application
- In technical terms: It uses the SQL View just like the old application, but always exports all columns and in the order that the view gives the columns.

Differences to old:

- [ ] Column headers are different: Old version has all capitalized letters, but possibly also sometimes edited names, meaning not directly the database columns
- [ ] Selection of columns is always the same: new app exports all columns that are in the SQL view; old app makes different selections based on who is exporting and with what settings
- [ ] Order of columns is different
- [ ] What settings should be brought into new app? Now you can filter based on localities only, but cannot select for example only now_ls or com_species, also cannot export the species that are not assigned to any locality.
- [ ] Mesowear score may not work right now - Does it need to be calculated in code or is it done in view?

**Comment by iritmaximus** [comment]
This feature is not used anymore as we have cross-search. Closing as not planned.
