### ISSUE TITLE
Locality: Check required fields

### ISSUE THREAD

**Issue by karilint** [nowcommunity/nowdatabase#182]
Record must have
- Name
- Country (a country picker)
- Maximum Age must be a positive real value.
- Minimum Age must be a positive real value.
- Basis for Age: Absolute for the minimum row must be set.
- Basis for Age: Absolute for the maximum row must be set.
- Latitude dms must be entered with positive numbers in format DD MM SS N or DD MM SS S.
- Longitude dms must be entered with positive numbers in format DDD MM SS E or DDD MM SS W.

Currently, the archaeology tab needs to be filled when creating a locality or the backend fails. This should not be the case.

**Comment by realtalin** [comment]
Being tracked in #257 and #270

**Comment by iritmaximus** [comment]
#257 and #270 closed.
