### ISSUE TITLE
User can edit existing time bounds without a reference

### ISSUE THREAD

**Issue by kaarleol** [nowcommunity/nowdatabase#183]
Add functionality for editing existing time bounds. 

- Editing a time bound should update the the time units AND localities using the time bound.
- Editing a time bound should leave a log entry to the time bound, time units using the time bound and the localities using the affected time units

Related to #173

**Comment by iritmaximus** [comment]
- [ ] User without editing rights cannot edit time bounds
- [ ] User with editing rights can edit time bounds with valid inputs
- [ ] User with editing rights and *incorrect* input cannot edit time bounds and is notified about it
- [ ] User with editing rights and *incorrect* input is notified about it
- [ ] Tests are implemented
- [ ] Documentation is written

**Comment by juhanikat** [comment]
- [ ] #277 
- [ ] #278

**Comment by juhanikat** [comment]
Started in sprint 2, continued in sprint 3

**Comment by juhanikat** [comment]
- [ ] #298 
- [ ] #328 
- [ ] #321 
- [ ] #277 
- [ ] #278

**Comment by kaarleol** [comment]
Continued in sprint 4

**Comment by karilint** [comment]
Test results:
- [x] OK: User without editing rights cannot edit time bounds
- [x] OK: User with editing rights can edit time bounds with valid inputs
- [x] OK: User with editing rights and *incorrect* input cannot edit time bounds and is notified about it
- [x] OK: User with editing rights and *incorrect* input is notified about it
- [x] OK: User cannot edit time bound that produces a contradiction in localities
- [x] OK: Editing time bounds updates time units
- [x] OK: After successfully editing, logs are updated correctly
- [x] Possibly OK: Tests are implemented
- [x] OK: Documentation is written

Time Bound (other notes):

- Time Units tab: a link to a Time Unit is required
- When creating contradicting ages that affect Localities or Time Units, the error message stays only for couple of seconds which is not very helpful
