### ISSUE TITLE
Selecting the minimum and maximum age of a locality by selecting a time unit for it works

### ISSUE THREAD

**Issue by kaarleol** [nowcommunity/nowdatabase#184]
Add functionality so that selecting a time unit for a locality automatically sets the corresponding age.

Updating a time unit should change all localities using the time unit. Updating a time unit should leave a log entry for the affected localities.

**Comment by iritmaximus** [comment]
Tracked in #256. Done in #389.

**Comment by karilint** [comment]
**Test results**

- [x] OK
