### ISSUE TITLE
User should be able to set a the minimum and maximum age of a locality to a fraction of the selected time unit

### ISSUE THREAD

**Issue by kaarleol** [nowcommunity/nowdatabase#185]
Add functionality so the minimum and maximum age of a locality are automatically calculated using the entered fraction of age.

User should be able to select one of the existing options (1:2, 2:2, 1:3, 2:3, 3:3) or manually write a fraction up to ninths (1:9-9:9)

**Comment by iritmaximus** [comment]
Is partially already implemented. Replaced by #462 and #463.
