### ISSUE TITLE
Bug: Locality validators incomplete

### ISSUE THREAD

**Issue by EeroAnt** [nowcommunity/nowdatabase#228]
Locality entries require values for:
**Age-tab**
- absolute min age
- absolute max age

**Locality-tab**
- name
- country
- latitude (dec) **missing**
- longitude (dec) **missing**

**Archeology-tab**
- Stone tool cut marks on bones **missing**
- Bipedal footprints **missing**
- Stone tool technology **missing**

**Comment by juhanikat** [comment]
Closing this since these have validators now, or in the case of archeology-tab buttons, default values.
