### ISSUE TITLE
User can customize what columns are shown and is able to view all columns available

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#234]

**Comment by iritmaximus** [comment]
- [ ] User can select all fields available
- [ ] User is initially shown default columns
- [ ] Tests are implemented
- [ ] Documentation is written

**Comment by EeroAnt** [comment]
- [ ] #239 
- [ ] #240
- [ ] #242
- [ ] #241
- [ ] #243
- [ ] #244
- [ ] #245
- [ ] #246

**Comment by karilint** [comment]
Works.

For the next round?
- some fields should be obligatory. Now all fields can be empty
- could the previous field selection be stored for the next time the user visits the page?
