### ISSUE TITLE
define default columns to hide for different tables

### ISSUE THREAD

**Issue by EeroAnt** [nowcommunity/nowdatabase#244]
every table should have variables columns and hiddenColumns. If a column is given an id, it can be hidden by adding it to the hiddenColumns variable.

![Image](https://github.com/user-attachments/assets/d1ca85a5-9c8a-4953-90bb-ad731702d2ef)
![Image](https://github.com/user-attachments/assets/b0fb9358-cd38-4b7b-b57a-64abdff263b3)

**Comment by EeroAnt** [comment]
this after can be done only after #241

**Comment by iritmaximus** [comment]
Implemented in #247.
