### ISSUE TITLE
Add validators for required fields for localities

### ISSUE THREAD

**Issue by realtalin** [nowcommunity/nowdatabase#270]
Currently only max and min age, name, country and dating method are required. Validators need to be added to match old php version, for example coordinates.

**Comment by realtalin** [comment]
Added small check for time not being negative, coordinate validation will be easier to do once coordinate conversion is done. Validating a decimal (dec) coordinate is trivial, while dms is not, so if auto-conversion is online only the trivial case is needed.

**Comment by karilint** [comment]
**Test results**

- [x] OK
