### ISSUE TITLE
User cannot press "Finalize entry" while editing if validators don't pass

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#370]

**Comment by juhanikat** [comment]
- [ ] User cannot click the button if there are any validation errors in any tabs
- [ ] User can click the button if there are no validation errors
- [ ] Existing tests are changed/new tests are written
- [ ] Documentation is written

**Comment by juhanikat** [comment]
- [ ] #428

**Comment by iritmaximus** [comment]
Continued work in Sprint 5

**Comment by karilint** [comment]
Test results:
- [x] User cannot click the button if there are any validation errors in any tabs
- [x] User can click the button if there are no validation errors
- [x] Existing tests are changed/new tests are written
- [x] Documentation is written

**Comment by realtalin** [comment]
docs here:

https://github.com/nowcommunity/nowdatabase/blob/main/documentation/components/frontend.md

**Comment by karilint** [comment]
**Test results:**
OK
