### ISSUE TITLE
User can select a country from a dropdown while adding/editing a locality

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#372]

**Comment by juhanikat** [comment]
- [ ] User is shown a list of countries
- [ ] User can click on a country to select it
- [ ] User can search the dropdown list to filter it
- [ ] Tests are implemented
- [ ] Documentation is written

**Comment by realtalin** [comment]
Implemented in #553

**Comment by karilint** [comment]
Test results: **Approved**
- [x] OK: User is shown a list of countries
- [x] OK: User can click on a country to select it
- [x] OK: User can search the dropdown list to filter it
- [x] Possibly OK: Tests are implemented
- [x] Possibly OK: Documentation is written 
-  could not find it. Possibly one can add a link to it when defined as Done

**Comment by realtalin** [comment]
docs for the component that was made for this are [here](https://github.com/nowcommunity/nowdatabase/blob/main/documentation/editingComponents/DropdownSelectorWithSearch.md)

**Comment by karilint** [comment]
Document **OK**
