### ISSUE TITLE
Implement a search box into the coordinate selection map

### ISSUE THREAD

**Issue by realtalin** [nowcommunity/nowdatabase#502]
~Current leading idea is to use the Photon api by Komoot. There is a ready-built leaftlet plugin for using the API: https://github.com/komoot/leaflet.photon~

~Edit: Using that with react-leaflet seems to be quite the headache, we are trying leaflet-geosearch now~

Decided to make our own implementation

**Comment by iritmaximus** [comment]
Done in #532
