### ISSUE TITLE
Country picking things

### ISSUE THREAD

**Issue by ShootingStar91** [nowcommunity/nowdatabase#78]
this is one option
https://github.com/driaug/country-picker

also need something for checking coordinates fall within right country. maybe 
https://github.com/simonepri/country-iso

**Comment by iritmaximus** [comment]
Related and very relevant to #372. Making a new issue for the coordinate country check.

**Comment by iritmaximus** [comment]
Feature implemented in #553 so this is not needed anymore. Closing.
