### ISSUE TITLE
Displaying boolean values

### ISSUE THREAD

**Issue by karilint** [nowcommunity/nowdatabase#89]
For example, Locality > Projects > Records

The records field is boolean (1/0) but the current list does not show anything (Private/Public).
There are other boolean fields with y/n (for example, now_loc.gen_loc)

**Comment by ShootingStar91** [comment]
[aed047f](https://github.com/nowcommunity/nowdatabase/commit/aed047fd7d76b965fb80aeea6cc16cfed7bcfa94)
